### ISSUE TITLE
Use feathericons/feather

### ISSUE THREAD

**Issue by addison-grant** [iFixit/toolbox#61]
We are resolving our dependency on iFixit/feather in https://github.com/iFixit/ifixit/pull/36203. Once that's merged, it seems like we can start using the feather-icons package in the public NPM registry.

```diff
- "feather-icons": "github:iFixit/feather",
+ "feather-icons": "<semver num.>",
```

Blocked on https://github.com/iFixit/ifixit/issues/36200

**Comment by addison-grant** [comment]
https://github.com/iFixit/ifixit/pull/36203 was merged, which unblocks this.

**Comment by addison-grant** [comment]
@andyg0808, I think I'll go ahead and open a PR for this. Should be as simple as uninstall our feather (delete the line from package.json), and then `npm install feather-icons`. Does that sound right? Then `npm install` and commit the package files?     And we'll want to look around and check where we're using toolbox and validate that they work fine with this change?

**Comment by andyg0808** [comment]
That sounds correct to me, @addison-grant.

**Comment by addison-grant** [comment]
Awesome. WIP.

**Comment by addison-grant** [comment]
Github advanced search to the rescue: `org:iFixit toolbox filename:package.json`

https://github.com/search?q=org%3AiFixit+toolbox+filename%3Apackage.json&type=Code&ref=advsearch&l=&l=

**Comment by addison-grant** [comment]
I believe this was done as of merging of #62, #63, and `npm publish`.
