### ISSUE TITLE
0.0.0-development to 1.1.1 change

### ISSUE THREAD

**Issue by addison-grant** [iFixit/toolbox#64]
I am not sure why the version used to be set to `0.0.0-development` in the `package.json` file. I accidentally changed it when I was publishing the package. The last commit on `master` didn't update NPM, and I'm not sure why.

https://github.com/iFixit/toolbox/commit/d52ef4196600a271db604a504ffdf763eb94fb94#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3

I don't know if it needs to be set back to `0.0.0-development`.

@sterlinghirsh, I wonder if you have any ideas about why it was set to `0.0.0-development` before, and if we need to change it back for some reason.

**Comment by sterlinghirsh** [comment]
Yeah I think semantic-release is supposed to be in charge of setting that as part of the push to npm. Guessing that's why it didn't update npm.

**Comment by addison-grant** [comment]
Alright, I'll set aside some time to look into this later this week.

**Comment by addison-grant** [comment]
I did a little testing, and it looks like version does need to be set to "0.0.0-development" in order for Semantic Release to work as expected with our current configuration (default semantic-release config). I dropped the last commit which changed the version to 1.1.1. It appears semantic-release uses tags to track versions.
