### ISSUE TITLE
Fix `innerRef` logic from glamorous cutover

### ISSUE THREAD

**Issue by djmetzle** [iFixit/toolbox#65]
Stub.

See: https://github.com/iFixit/ifixit/pull/36586

CC @sterlinghirsh @sctice @andyg0808

**Comment by sterlinghirsh** [comment]
I don't think there's any fix necessary here. We were only using this to be able to blur the element on submit, but that's handled another way now. All these elements will be replaced soonish anyway, so I'm going to close this and @djmetzle can reopen if necessary.
